version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sahayak-ai-backend"
s3_prefix = "sahayak-ai-backend"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = ""
image_repositories = []
